trigger:
  branches:
    include:
    - master
  paths:
    include:
    - add-two-numbers-exercise/templates/
    - add-two-numbers-exercise/add-two-numbers-templated.yaml

pool:
  vmImage: "ubuntu-20.04"

steps:
- template: templates/add-two-numbers-template.yaml
  parameters:
    firstNumber: 6
    secondNumber: 3