# triggers define how the pipeline can be executed.
trigger:
  # pipelines will trigger when changes are observed
  # in the following included branches and included paths.
  branches:
    include:
    - master
  paths:
    include:
    - add-two-numbers-exercise/templates/
    - add-two-numbers-exercise/add-two-numbers-templated.yaml

# the pool decides the agent the pipeline execution will use
# there are of two types: Microsoft-hosted agents and self-hosted agents.
pool:
  vmImage: "ubuntu-20.04"

# pipeline execution happens in steps and each step can
# be described like below.
steps:
# we can reference a pipeline template using the 'template' task.
# the pipeline template must be present at the path provided to the template task.
- template: templates/add-two-numbers-template.yaml
  parameters:
    firstNumber: 6
    secondNumber: 3